### ISSUE TITLE
Search not working!?

### ISSUE THREAD

**Issue by ambs** [elastic/elasticsearch-perl#207]
Hi. Using the new 7 release (7.712).
Trying this query:
```
my $results = $es->search(
    index => 'test',
    body => {
        query => {
            "match_all" => {}
   }});
```
Return 0 documents.

But this:

```
curl -H "Content-Type: application/json" http://127.0.0.1:9200/test/_search/-X POST -d '{"query":{"match_all":{}}}'
```

works. 
Any idea what I am doing wrong?

**Comment by ambs** [comment]
Similar problem with the `explain` method:
```
[Missing] ** [http://127.0.0.1:9200]-[404] Not Found, called from sub Search::Elasticsearch::Role::Client::Direct::__ANON__ at teste.pl line 63. With vars: {'request' => {'qs' => {},'body' => {'query' => {'match_all' => {}}},'method' => 'GET','path' => '/test/_explain/1','mime_type' => 'application/json','serialize' => 'std','ignore' => []},'status_code' => 404,'body' => {'matched' => bless( do{\(my $o = 0)}, 'JSON::PP::Boolean' ),'_id' => '1','_type' => '_doc','_index' => 'test'}}
```
when using
```

my $results = $es->explain(
    index => 'test',
    id => 1,
    body => {
        query => {
            "match_all" => {}
    } } } );
```

But working as curl:
```
curl -H "Content-Type: application/json" http://127.0.0.1:9200/test/_explain/1 -X POST -d '{"query":{"match_all":{}}}'
```

**Comment by ambs** [comment]
This is a simple test case, running with Docker.
The Perl code is in https://gist.github.com/ambs/80ce76d5ef4471476d70d958c4f3921e
The docker-file I am using, in case it helps:
```
version: '3'
services:
    # search engine
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
        container_name: elasticsearch
        environment:
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
            - 'discovery.type=single-node'
        ports:
            - '9200:9200'
            - '9300:9300'
```

An Interesting thing is that, in the end, if I run the `curl` debugging code, I get the right output.
Do I need to run some kind of "sync" or "flush"?
